// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_task_project.Core;

namespace Test_task_project.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Test_task_project.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            Name = "Tom"
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 3,
                            Active = false,
                            Name = "Mike"
                        },
                        new
                        {
                            Id = 4,
                            Active = false,
                            Name = "Bill"
                        },
                        new
                        {
                            Id = 5,
                            Active = false,
                            Name = "Sam"
                        },
                        new
                        {
                            Id = 6,
                            Active = false,
                            Name = "Barry"
                        },
                        new
                        {
                            Id = 7,
                            Active = false,
                            Name = "Marry"
                        },
                        new
                        {
                            Id = 8,
                            Active = false,
                            Name = "Donald"
                        },
                        new
                        {
                            Id = 9,
                            Active = false,
                            Name = "Jerry"
                        },
                        new
                        {
                            Id = 10,
                            Active = false,
                            Name = "Fill"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
